- name: Cittadino
  image: /assets/images/citizen.jpg
  metaname: cittadini

- name: Impresa
  image: /assets/images/pa.jpg
  metaname: imprese

- name: Intermediario
  image: /assets/images/professionist.jpg
  metaname: intermediari

- name: Pubblica Amministrazione
  image: /assets/images/professionist.jpg
  metaname: pa
